# Generated by Django 2.1.7 on 2019-02-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies_app', '0002_asanimza_companycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, verbose_name='qeydler')),
                ('doc_date', models.DateField()),
                ('doc_expr_date', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'yarandi'), (2, 'gonderen imzaldir'), (3, 'qebul eden imzaldir'), (4, 'qebul eden imtina etdi'), (5, 'vaxti bitib')], default=1)),
                ('doc_send_date', models.DateTimeField(auto_now=True)),
                ('doc_file', models.FileField(upload_to='docs')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_cod_set', to='companies_app.Company')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_doc_set', to='companies_app.Company')),
            ],
        ),
    ]
